
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action quitAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Image PokemonImage1;
	
	private global::Gtk.ComboBoxEntry PokemonSlot1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Image PokemonImage2;
	
	private global::Gtk.ComboBoxEntry PokemonSlot2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Image PokemonImage3;
	
	private global::Gtk.ComboBoxEntry PokemonSlot3;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Image PokemonImage4;
	
	private global::Gtk.ComboBoxEntry PokemonSlot4;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Image PokemonImage5;
	
	private global::Gtk.ComboBoxEntry PokemonSlot5;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Image PokemonImage6;
	
	private global::Gtk.ComboBoxEntry PokemonSlot6;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Button ProposeButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Datei");
		w1.Add (this.FileAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.quitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Pokemon Team Builder");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='quitAction' action='quitAction'/></menu><menuitem name='SettingsAction' action='SettingsAction'/><menuitem name='HelpAction' action='HelpAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.PokemonImage1 = new global::Gtk.Image ();
		this.PokemonImage1.Name = "PokemonImage1";
		this.hbox1.Add (this.PokemonImage1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PokemonImage1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.PokemonSlot1 = global::Gtk.ComboBoxEntry.NewText ();
		this.PokemonSlot1.Name = "PokemonSlot1";
		this.hbox1.Add (this.PokemonSlot1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PokemonSlot1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.PokemonImage2 = new global::Gtk.Image ();
		this.PokemonImage2.Name = "PokemonImage2";
		this.hbox2.Add (this.PokemonImage2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.PokemonImage2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.PokemonSlot2 = global::Gtk.ComboBoxEntry.NewText ();
		this.PokemonSlot2.Name = "PokemonSlot2";
		this.hbox2.Add (this.PokemonSlot2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.PokemonSlot2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.PokemonImage3 = new global::Gtk.Image ();
		this.PokemonImage3.Name = "PokemonImage3";
		this.hbox3.Add (this.PokemonImage3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.PokemonImage3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.PokemonSlot3 = global::Gtk.ComboBoxEntry.NewText ();
		this.PokemonSlot3.Name = "PokemonSlot3";
		this.hbox3.Add (this.PokemonSlot3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.PokemonSlot3]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.PokemonImage4 = new global::Gtk.Image ();
		this.PokemonImage4.Name = "PokemonImage4";
		this.hbox4.Add (this.PokemonImage4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.PokemonImage4]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.PokemonSlot4 = global::Gtk.ComboBoxEntry.NewText ();
		this.PokemonSlot4.Name = "PokemonSlot4";
		this.hbox4.Add (this.PokemonSlot4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.PokemonSlot4]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.PokemonImage5 = new global::Gtk.Image ();
		this.PokemonImage5.Name = "PokemonImage5";
		this.hbox5.Add (this.PokemonImage5);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.PokemonImage5]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.PokemonSlot5 = global::Gtk.ComboBoxEntry.NewText ();
		this.PokemonSlot5.Name = "PokemonSlot5";
		this.hbox5.Add (this.PokemonSlot5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.PokemonSlot5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.PokemonImage6 = new global::Gtk.Image ();
		this.PokemonImage6.Name = "PokemonImage6";
		this.hbox6.Add (this.PokemonImage6);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.PokemonImage6]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.PokemonSlot6 = global::Gtk.ComboBoxEntry.NewText ();
		this.PokemonSlot6.Name = "PokemonSlot6";
		this.hbox6.Add (this.PokemonSlot6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.PokemonSlot6]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
		w20.Position = 6;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.ProposeButton = new global::Gtk.Button ();
		this.ProposeButton.CanFocus = true;
		this.ProposeButton.Name = "ProposeButton";
		this.ProposeButton.UseUnderline = true;
		this.ProposeButton.Label = global::Mono.Unix.Catalog.GetString ("Propose Team");
		this.hbox7.Add (this.ProposeButton);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ProposeButton]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox1.Add (this.hbox7);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
		w22.Position = 7;
		w22.Expand = false;
		w22.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 792;
		this.DefaultHeight = 549;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnExit);
		this.ProposeButton.Clicked += new global::System.EventHandler (this.OnProposeTeam);
	}
}
